/**
 * Mock fleet data for the NER Logistics live tracking demo.
 * Simulates real GPS-updated truck positions near Guwahati, Assam.
 */

export const FLEET_TRUCKS = [
  {
    id: 'TRK-4421',
    driverName: 'Rajan Sharma',
    cargo: 'Pharma',
    cargoIcon: '💊',
    delayRisk: 78,
    status: 'REROUTED',
    route: 'NH27 → NH17 (Dynamic)',
    lat: 26.1721,
    lng: 91.7458,
    heading: 42,
    eta: '14:30',
    rerouted: true,
  },
  {
    id: 'TRK-3387',
    driverName: 'Bikash Das',
    cargo: 'Food Grains',
    cargoIcon: '🌾',
    delayRisk: 23,
    status: 'ON_ROUTE',
    route: 'NH27 (Clear)',
    lat: 26.1445,
    lng: 91.7362,
    heading: 90,
    eta: '16:00',
    rerouted: false,
  },
  {
    id: 'TRK-5502',
    driverName: 'Amit Nath',
    cargo: 'Medical Supplies',
    cargoIcon: '🏥',
    delayRisk: 91,
    status: 'DELAYED',
    route: 'NH27 (Blocked — Landslide)',
    lat: 26.1900,
    lng: 91.7800,
    heading: 270,
    eta: '18:45',
    rerouted: false,
  },
  {
    id: 'TRK-2209',
    driverName: 'Pranab Gogoi',
    cargo: 'Electronics',
    cargoIcon: '📦',
    delayRisk: 12,
    status: 'ON_ROUTE',
    route: 'NH37 (Clear)',
    lat: 26.1200,
    lng: 91.6900,
    heading: 135,
    eta: '13:15',
    rerouted: false,
  },
  {
    id: 'TRK-6678',
    driverName: 'Suresh Baruah',
    cargo: 'Fuel',
    cargoIcon: '⛽',
    delayRisk: 55,
    status: 'REROUTED',
    route: 'NH37 → NH17 (Dynamic)',
    lat: 26.2100,
    lng: 91.7200,
    heading: 200,
    eta: '15:00',
    rerouted: true,
  },
  {
    id: 'TRK-1144',
    driverName: 'Dipjyoti Kalita',
    cargo: 'Vegetables',
    cargoIcon: '🥬',
    delayRisk: 38,
    status: 'ON_ROUTE',
    route: 'NH27 (Light Traffic)',
    lat: 26.1600,
    lng: 91.7600,
    heading: 60,
    eta: '14:45',
    rerouted: false,
  },
];

export const REROUTE_TIMELINE = [
  {
    id: 'RT-001',
    truckId: 'TRK-4421',
    timestamp: '09:42 AM',
    reason: 'Landslide on NH27 — KM 214',
    newRoute: 'NH17 via Nalbari',
    aiConfidence: 94,
  },
  {
    id: 'RT-002',
    truckId: 'TRK-6678',
    timestamp: '08:15 AM',
    reason: 'Flood risk on NH37 bridge',
    newRoute: 'NH17 via Boko',
    aiConfidence: 87,
  },
  {
    id: 'RT-003',
    truckId: 'TRK-3387',
    timestamp: '07:30 AM',
    reason: 'Preventive — Heavy rain forecast',
    newRoute: 'NH27 maintained (low risk)',
    aiConfidence: 71,
  },
];

export const KPI_DATA = {
  activeTrips: 6,
  runningFleet: 5,
  criticalRisks: 2,
  reroutes: 2,
  onTimeRate: 83,
};
